import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { calculateStreak } from "@/lib/reading-stats";

const MILESTONES = [3, 7, 14, 30] as const;
const MILESTONE_XP: Record<number, number> = { 3: 30, 7: 75, 14: 150, 30: 300 };

export async function GET() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const [{ data: sessions }, { data: profile }, { data: todaySpin }, { data: claims }, { count: referralCount }] =
    await Promise.all([
      supabase.from("reading_sessions").select("date, minutes_read").eq("user_id", user.id),
      supabase.from("users").select("referral_code").eq("id", user.id).single(),
      supabase
        .from("daily_spins")
        .select("xp_awarded")
        .eq("user_id", user.id)
        .eq("spin_date", new Date().toISOString().slice(0, 10))
        .maybeSingle(),
      supabase.from("streak_reward_claims").select("streak_milestone").eq("user_id", user.id),
      supabase.from("referral_rewards").select("id", { count: "exact", head: true }).eq("referrer_id", user.id).eq("status", "rewarded"),
    ]);

  const streak = calculateStreak(sessions ?? []);
  const claimedMilestones = new Set((claims ?? []).map((c) => c.streak_milestone));

  // Referral codes are generated by a SECURITY DEFINER RPC so RLS cannot
  // silently prevent a kid from getting their own code.
  let referralCode = profile?.referral_code ?? null;
  if (!referralCode) {
    const { data: generatedCode } = await supabase.rpc("get_or_create_referral_code", {
      p_user_id: user.id,
    });
    referralCode = generatedCode ?? null;
  }

  return NextResponse.json({
    streak,
    milestones: MILESTONES.map((m) => ({
      milestone: m,
      xp: MILESTONE_XP[m],
      reached: streak >= m,
      claimed: claimedMilestones.has(m),
    })),
    todaySpinXp: todaySpin?.xp_awarded ?? null,
    referralCode,
    successfulReferrals: referralCount ?? 0,
  });
}
